
### Dang ky
POST http://localhost:8080/api/auth/signup 
Content-Type: application/json

{
    "username": "liem111",
    "fullname":"Nguyễn Tuấn Liêm",
    "email":"liem123@gmail.com",
    "password":"123123"
}
### Dang nhap
POST http://localhost:8080/api/auth/signin 
Content-Type: application/json

{
    "username": "thang111", 
    "password":"123123"
}
###Doi quyen cua nguoi dung
PUT http://localhost:8080/api/auth/64b75f34581042c76dec6d1c
Content-Type: application/json

{
    "role":"admin"
}
### Thong tin nguoi dung
GET http://localhost:8080/api/users/userinfo?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0YjgxMWI4ZDM3NWRmYThkMGUwY2YxMiIsImlhdCI6MTY5NDMxNzIwNiwiZXhwIjoxNjk0NDAzNjA2fQ.uVjRWS04tiO9_Sakol3UCrH7_w4fiOvNzg5kA34jns8
### Doi mat khau
PUT http://localhost:8080/api/auth/64b631c31de14e3e3eb41813/password
Content-Type: application/json

{
  "userId": "64b631c31de14e3e3eb41813",
  "currentPassword": "123123",
  "newPassword": "161101"
}
### Xem ke hoach
GET http://localhost:8080/api/projects

### Them ke hoach
POST http://localhost:8080/api/projects?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0YjgxMWI4ZDM3NWRmYThkMGUwY2YxMiIsImlhdCI6MTY5MzQwOTI2OCwiZXhwIjoxNjkzNDk1NjY4fQ.uwU0-y-gGpGEl_KFZcmdwg5Gk-_oVrgtYhKrasl-5h4
Content-Type: application/json

{
    "title": "Kế Hoạch 3",
    "description": "Nội dung kế hoạch 3",
    "startDate": "2023-9-25",
    "endDate": "2023-10-25",
    "budget": 10000
}
###
POST http://localhost:8080/api/projects
Content-Type: application/json

{
    "title": "Kế Hoạch 3",
    "description": "Nội dung kế hoạch 3",
    "startDate": "2023-9-25",
    "endDate": "2023-10-25",
    "budget": 10000
}

### Sua ke hoach
PUT http://localhost:8080/api/projects/64e1a654f61443b157af7e02?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0YjgxMWI4ZDM3NWRmYThkMGUwY2YxMiIsImlhdCI6MTY5Mjg4MTY1OCwiZXhwIjoxNjkyOTY4MDU4fQ.GnnKtCCVhOhNV2iv1pD0vQal8n0ToWgL3Y02YG-JTfo

{
    "title": "Ke hoach 2 updatdsadasded",
    "description": "222222",
    "startDate": "2023-09-01",
    "endDate": "2023-11-30",
    "budget": 6000
} 
### Xoa ke hoach
DELETE http://localhost:8080/api/projects/64d3a6535113b2cf8e7b87ba?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0Yjc1ZjM0NTgxMDQyYzc2ZGVjNmQxYyIsImlhdCI6MTY5MTc0MDgxMSwiZXhwIjoxNjkxODI3MjExfQ.bSPR2ZzTKEdl3SuOjgIzi_13T2-9VB9IbqZRwuwmnB0
### Xem ke hoach cua nhan vien

GET http://localhost:8080/api/projects/nv?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0YjgxMWI4ZDM3NWRmYThkMGUwY2YxMiIsImlhdCI6MTY5MzI3OTAwOCwiZXhwIjoxNjkzMzY1NDA4fQ.7N_KDlU50ngauEVtIHuCELzveg27t3rZwM6uGY6A8Ro

### Them cong viec

POST http://localhost:8080/api/tasks/
Content-Type: application/json

{
  "board_id": "64c3b069f5cc276bb4360e71",
  "title": "Công việc 11",
  "description": "Nội dung công việc 11",
  "dueDate": "2023-08-15",
  "members":["64b811b8d375dfa8d0e0cf12"]
}

### Xem cong viec
GET http://localhost:8080/api/tasks

### Xem cong viec theo bang cong viec
GET http://localhost:8080/api/tasks/64c3b3f4ca280774e57d0d97

### Xoa cong viec
DELETE http://localhost:8080/api/tasks/64c4947575d09cc91f1ee4a2
### Sua cong viec

PUT http://localhost:8080/api/tasks/64c497992e1ff91ebfebefe0
Content-Type: application/json

{
    "title": "Công việc 5",
    "description": "Nội dung công việc 5",
    "members":["64b811b8d375dfa8d0e0cf12","64b811eed375dfa8d0e0cf16"]
} 
### Tự động sửa công việc
POST http://localhost:8080/api/tasks/updateStatus
### Xem cong viec cua nhan vien
GET http://localhost:8080/api/tasks/nv?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0YjgxMWI4ZDM3NWRmYThkMGUwY2YxMiIsImlhdCI6MTY5NDQwNTU1MiwiZXhwIjoxNjk0NDkxOTUyfQ.kPFKoAd33Xfdj35S6lq3m-jjVhpHKfSHYBkx7PY6Nks

### Danh sach nhan vien
GET http://localhost:8080/api/users/


### Them bang cong viec
POST http://localhost:8080/api/boards?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0YjgxMWI4ZDM3NWRmYThkMGUwY2YxMiIsImlhdCI6MTY5MzQ4OTUxOCwiZXhwIjoxNjkzNTc1OTE4fQ.LenMmpdw9RrJgzjxXmd4msvtEY9qKQsFPVnv0BGyAOI
Content-Type: application/json

{
  "board_name": "BCV 2 của kế hoạch 2",
  "project": "64d076062d4ee8a99f2194eb",
  "board_leader": "64b75f34581042c76dec6d1c"
}
### Danh sach bang cong viec
GET  http://localhost:8080/api/boards/

###Danh sach bang cong viec cua 1 project
GET  http://localhost:8080/api/boards/651d2fc97cbcf5ecba9e2838

###Danh sach bang cong viec cua 1 leader
GET  http://localhost:8080/api/boards/bb?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0YjgxMWI4ZDM3NWRmYThkMGUwY2YxMiIsImlhdCI6MTY5MzQ4OTUxOCwiZXhwIjoxNjkzNTc1OTE4fQ.LenMmpdw9RrJgzjxXmd4msvtEY9qKQsFPVnv0BGyAOI
### Chinh sua bang cong viec
PUT http://localhost:8080/api/boards/64f099e07e9ce59190bbc65a?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0Yjc1ZjM0NTgxMDQyYzc2ZGVjNmQxYyIsImlhdCI6MTY5MzU3NzE0OCwiZXhwIjoxNjkzNjYzNTQ4fQ.YSnptcSSh7b-TKVWVR4GgI8sx9b69QFwtlG8Ga4arb0
Content-Type: application/json

{
  "board_name": "BCV của kế hoạch 1115457811"
}

### Xoa bang cong viec
DELETE http://localhost:8080/api/boards/64f03b1fea0f1b3e87fd1440
### Them Comment
POST http://localhost:8080/api/comments?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0YjgxMWI4ZDM3NWRmYThkMGUwY2YxMiIsImlhdCI6MTY5MTEyMzk4OCwiZXhwIjoxNjkxMjEwMzg4fQ.Q6ngGBUyAgOv-ppe9MqIPA4udHfOBB7SyIy8uMc06vw
Content-Type: application/json

{
  "task_id": "64c497992e1ff91ebfebefe0",
  "comment_text": "Bai tap nay bo ich"
}
### Xem tat ca comment
GET http://localhost:8080/api/comments

### Xem tat ca comment theo task id
GET http://localhost:8080/api/comments/64c8787d91d4993cdc3fa19e
### Xem tat ca bao cao cua mot nhan vien
GET http://localhost:8080/api/reports?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0YjgxMWI4ZDM3NWRmYThkMGUwY2YxMiIsImlhdCI6MTY5MjcwOTg0NCwiZXhwIjoxNjkyNzk2MjQ0fQ.4u_eMIoa2Na5hsVlC0T6UII6LhS2BSXbhbNxl8squDk
### Xem tat ca bao cao cua mot task
GET http://localhost:8080/api/reports/64c497992e1ff91ebfebefe0
### Thêm báo cáo
POST http://localhost:8080/api/reports?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0YjgxMWI4ZDM3NWRmYThkMGUwY2YxMiIsImlhdCI6MTY5Mjc2NjIzMywiZXhwIjoxNjkyODUyNjMzfQ.LU8Ftz3vlt_Jf5J9dpomYoWxVIjf_JOdISvXtuCtAZM
Content-Type: application/json

{
  "title": "Báo cáo tổng kết 22",
  "description": "Báo cáo tổng kết hoạt động trong tháng",
  "project": "64d076062d4ee8a99f2194eb",
  "task": "61503e4f9a3e9e001fd7f1b3"
}
### Xóa báo cáo
DELETE http://localhost:8080/api/reports/64e59024f1a3d7dd5729de04
